In [1]:
from google.colab import files
uploaded = files.upload()

Saving diabetes.csv to diabetes.csv


In [4]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score,StratifiedKFold

In [5]:
dataframe = pd.read_csv('diabetes.csv')
dataframe

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [ ]:
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y)

In [11]:
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((614, 8), (614,), (154, 8), (154,))

In [15]:
clf = SVC()
clf.fit(X_train,Y_train)

SVC()

In [16]:
Y_predict = clf.predict(X_test)

In [18]:
print(classification_report(Y_test,Y_predict))

              precision    recall  f1-score   support

         0.0       0.76      0.90      0.83       100
         1.0       0.72      0.48      0.58        54

    accuracy                           0.75       154
   macro avg       0.74      0.69      0.70       154
weighted avg       0.75      0.75      0.74       154



In [20]:
accuracy_score(Y_train, clf.predict(X_train))

0.7703583061889251

HYPER PARAMETER

In [31]:
clf = SVC()
param_grid = [{'kernel':['linear','rbf'],'gamma':[0.1,0.5,1],'C':[0.1,1,10]}]
Kfold = StratifiedKFold(n_splits=5)
gsv = RandomizedSearchCV(clf,param_grid,cv=Kfold,scoring= 'recall')
gsv.fit(X_train,Y_train)

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=SVC(),
                   param_distributions=[{'C': [0.1, 1, 10],
                                         'gamma': [0.1, 0.5, 1],
                                         'kernel': ['linear', 'rbf']}],
                   scoring='recall')

In [32]:
gsv.best_params_, gsv.best_score_

({'kernel': 'linear', 'gamma': 1, 'C': 10}, np.float64(0.5421926910299003))

In [35]:
clf_model = SVC(kernel='linear',C=1)
clf_model.fit(X_train, Y_train)
y_pred = clf_model.predict(X_test)
acc = accuracy_score(Y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(Y_test, y_pred)



Accuracy = 75.97402597402598


array([[87, 13],
       [24, 30]])

In [38]:
y_pred

array([1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [40]:
confusion_matrix(Y_test, y_pred)

array([[87, 13],
       [24, 30]])